Add loadCharacters test
isdi-coders-2022/Espantapajaros-Lugubres-202209-bcn pull request #9
Opened 2022-10-24 18:22 UTC by carlosdelblanco

2022-10-24 18:26 UTC, pastordesoles approved these changes

2022-10-24 19:41 UTC, oriolraventosc requested changes
Muy bien el coverage del test! Te comento las cosas a modificar:
-El primer describe es muy genérico (especifica que action creator está siendo testeado)
-En el segundo describe con que nombres la palabra function ya hace referencia al action creator, por lo tanto no hace falta repetirlo.

2022-10-25 08:11 UTC, oriolraventosc approved these changes

2022-10-25 08:14 UTC, pastordesoles approved these changes

2022-10-25 09:07 UTC, merged